// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrIG6Q4OPl0E3Ic8ijQZMtkO2zzjuIby0',
    appId: '1:875966624692:web:337d86682767dfa82678e1',
    messagingSenderId: '875966624692',
    projectId: 'rotijugaad',
    authDomain: 'rotijugaad.firebaseapp.com',
    storageBucket: 'rotijugaad.appspot.com',
    measurementId: 'G-M0H6L0637T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiA7j53LVa2sw4B1qm-M0uzt9hj0DGquo',
    appId: '1:875966624692:android:af0c8c6241568e832678e1',
    messagingSenderId: '875966624692',
    projectId: 'rotijugaad',
    storageBucket: 'rotijugaad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRygmP5xZ7vGxorZBQf5puq-yIllajwsg',
    appId: '1:875966624692:ios:8a6e072acb9ba5932678e1',
    messagingSenderId: '875966624692',
    projectId: 'rotijugaad',
    storageBucket: 'rotijugaad.appspot.com',
    iosBundleId: 'com.webminix.rotijugaad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRygmP5xZ7vGxorZBQf5puq-yIllajwsg',
    appId: '1:875966624692:ios:8a6e072acb9ba5932678e1',
    messagingSenderId: '875966624692',
    projectId: 'rotijugaad',
    storageBucket: 'rotijugaad.appspot.com',
    iosBundleId: 'com.webminix.rotijugaad',
  );
}
